let { rock, roid } = require('../tiles/decoration.js'),
    { normal: ____, nest, wall } = require('../tiles/misc.js'),

room = [
    [wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall],
    [wall,nest,wall,nest,nest,nest,wall,nest,nest,nest,nest,nest,nest,nest,wall,nest,nest,nest,nest,nest,nest,wall,nest,nest,nest,wall,nest,nest,nest,wall],
    [wall,nest,wall,nest,wall,wall,wall,wall,wall,wall,wall,nest,wall,nest,wall,nest,wall,wall,wall,wall,nest,nest,nest,wall,nest,nest,nest,wall,nest,wall],
    [wall,nest,wall,nest,nest,nest,nest,wall,nest,wall,nest,nest,wall,nest,wall,nest,nest,nest,wall,nest,nest,wall,nest,wall,wall,wall,wall,wall,wall,wall],
    [wall,nest,wall,wall,wall,wall,nest,wall,nest,wall,wall,wall,wall,nest,nest,nest,wall,nest,wall,nest,wall,wall,nest,nest,nest,nest,nest,wall,nest,wall],
    [wall,nest,nest,wall,nest,nest,nest,wall,nest,wall,nest,nest,nest,nest,wall,nest,wall,wall,wall,nest,nest,wall,wall,wall,wall,wall,wall,wall,nest,wall],
    [wall,nest,nest,nest,nest,wall,wall,wall,nest,wall,wall,nest,wall,wall,wall,nest,nest,nest,wall,wall,nest,wall,nest,nest,nest,nest,nest,nest,nest,wall],
    [wall,wall,wall,wall,nest,wall,nest,nest,nest,nest,nest,nest,wall,nest,nest,nest,wall,nest,nest,nest,nest,wall,nest,wall,nest,wall,wall,nest,wall,wall],
    [wall,nest,nest,nest,nest,wall,nest,wall,wall,wall,nest,wall,wall,nest,wall,nest,wall,wall,wall,nest,nest,wall,nest,wall,nest,wall,nest,nest,nest,wall],
    [wall,nest,wall,nest,nest,wall,wall,wall,nest,nest,nest,wall,wall,nest,wall,nest,nest,nest,nest,nest,nest,nest,nest,wall,nest,wall,nest,wall,nest,wall],
    [wall,wall,wall,wall,nest,nest,wall,nest,nest,wall,nest,nest,wall,nest,nest,nest,wall,nest,wall,wall,wall,nest,wall,wall,nest,nest,nest,wall,nest,wall],
    [wall,nest,nest,wall,wall,nest,wall,nest,wall,wall,wall,nest,wall,wall,wall,nest,wall,nest,nest,nest,wall,nest,nest,nest,nest,nest,nest,wall,wall,wall],
    [wall,wall,nest,wall,nest,nest,nest,nest,wall,nest,wall,wall,wall,nest,wall,nest,wall,wall,wall,nest,nest,nest,wall,wall,wall,wall,nest,nest,nest,wall],
    [wall,nest,nest,wall,nest,wall,wall,nest,nest,nest,wall,wall,nest,nest,nest,nest,nest,wall,nest,nest,wall,nest,nest,wall,nest,nest,nest,wall,nest,wall],
    [wall,nest,nest,wall,nest,nest,wall,wall,wall,nest,wall,nest,nest,wall,nest,wall,nest,wall,nest,wall,wall,wall,nest,nest,nest,wall,nest,wall,wall,wall],
    [wall,nest,wall,wall,wall,nest,nest,nest,wall,nest,wall,nest,wall,wall,wall,wall,nest,nest,nest,nest,nest,wall,wall,nest,wall,wall,nest,nest,nest,wall],
    [wall,nest,wall,nest,wall,wall,nest,wall,nest,nest,wall,nest,wall,nest,wall,nest,nest,wall,nest,wall,nest,wall,nest,nest,nest,nest,nest,wall,nest,wall],
    [wall,nest,nest,nest,nest,nest,nest,wall,wall,nest,nest,nest,wall,nest,nest,nest,wall,wall,wall,wall,nest,nest,nest,wall,nest,wall,nest,wall,nest,wall],
    [wall,wall,nest,wall,wall,wall,nest,nest,nest,nest,wall,wall,wall,nest,wall,nest,nest,wall,nest,nest,nest,wall,wall,wall,nest,wall,wall,wall,nest,wall],
    [wall,wall,nest,nest,wall,nest,nest,nest,wall,nest,nest,nest,wall,wall,wall,wall,nest,wall,nest,wall,nest,wall,nest,nest,nest,wall,nest,wall,wall,wall],
    [wall,wall,wall,nest,wall,nest,wall,nest,wall,wall,wall,wall,wall,nest,nest,nest,nest,wall,nest,wall,nest,wall,nest,wall,nest,nest,nest,nest,nest,wall],
    [wall,wall,nest,nest,wall,wall,wall,nest,wall,nest,wall,nest,wall,nest,wall,nest,wall,wall,wall,wall,wall,wall,wall,wall,wall,nest,wall,wall,nest,wall],
    [wall,nest,nest,nest,wall,nest,wall,nest,wall,nest,nest,nest,wall,nest,wall,nest,nest,nest,nest,nest,nest,nest,nest,nest,nest,nest,wall,nest,nest,wall],
    [wall,wall,wall,nest,wall,nest,wall,nest,nest,nest,wall,wall,wall,wall,wall,wall,nest,wall,wall,nest,wall,nest,wall,wall,nest,wall,wall,wall,nest,wall],
    [wall,nest,nest,nest,wall,nest,wall,wall,wall,nest,nest,nest,wall,nest,nest,nest,nest,nest,wall,nest,wall,wall,wall,nest,nest,nest,nest,wall,wall,wall],
    [wall,nest,wall,nest,wall,nest,nest,nest,wall,wall,wall,nest,wall,nest,wall,wall,wall,wall,wall,nest,nest,nest,wall,wall,wall,wall,nest,wall,nest,wall],
    [wall,nest,wall,nest,wall,nest,wall,nest,wall,nest,nest,nest,nest,nest,wall,nest,nest,nest,nest,nest,wall,nest,nest,nest,nest,wall,nest,nest,nest,wall],
    [wall,nest,wall,wall,wall,nest,wall,nest,wall,nest,wall,wall,wall,nest,wall,wall,nest,wall,wall,nest,wall,nest,wall,nest,wall,wall,wall,nest,wall,wall],
    [wall,nest,nest,nest,nest,nest,wall,nest,nest,nest,wall,nest,nest,nest,wall,nest,nest,nest,nest,nest,wall,nest,wall,nest,nest,nest,wall,nest,nest,wall],
    [wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall,wall]
];

module.exports = room;
